# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_10; end
module ::Anonymous_Delegator_17; end
module ::Anonymous_Delegator_25; end
module ::Anonymous_Delegator_3; end
